### ISSUE TITLE
read pair handling

### ISSUE THREAD

**Issue by linsalrob** [shandley/hecatomb#10]
`bbtools` appears to only recognize `:1` & `:2` or `/1` & `/2` for read pairs. This breaks everything at step 6 when we run `repair.sh`

Many reads downloaded from SRA use `.1` and `.2`  to identify paired-end reads.

A simple solution is to rename all the reads before you begin to ensure that they end with `/1` and `/2` as appropriate. You can use [change_fastq_pair_symbol](https://github.com/linsalrob/EdwardsLab/blob/master/fastq/change_fastq_pair_symbol.c) to do that, but it is not the most elegant or efficient solution (but it works).

I am not sure where/how to implement a better fix for this, or if it is our responsibility to check read names,

**Comment by linsalrob** [comment]
The bowtie/samtools combination automatically adds `/1` and `/2` to the read pairs and so avoids this issue entirely (and doesn't use repair.sh because it extracts left and right reads separately from a single `.bam` file).

**Comment by shandley** [comment]
This wraps into a larger issue about using bbmap, which was originally selected due to integration with the bbtools package leaving us only with a single dependency for this part of the pipeline. It has become clear that the java memory management issues are potentially more trouble than it is worth for dependency simplicity.

The other reason to use bbmap was for the taxonomy integration sued in interrogating which bacteria were mapped in step_8. But when we move step_8 into it's own module it will be additional reason not to use bbmap in contaminant_removal.

If we just decide to go with bowtie for the host mapping can we close this issue?
