### ISSUE TITLE
Error: EOF marker is absent.There appear to be different numbers of reads in the paired input files

### ISSUE THREAD

**Issue by Leran10** [shandley/hecatomb#55]
Hi,

I ran Hecatomb (version beta4) on 141 paired-end samples, it crashed and gave this error message:

```
[W::bgzf_read_block] EOF marker is absent. The input may be truncated
java.lang.AssertionError: 
There appear to be different numbers of reads in the paired input files.
The pairing may have been corrupted by an upstream process. It may be fixable by running repair.sh.
    at stream.ConcurrentGenericReadInputStream.pair(ConcurrentGenericReadInputStream.java:498)
    at stream.ConcurrentGenericReadInputStream.readLists(ConcurrentGenericReadInputStream.java:363)
    at stream.ConcurrentGenericReadInputStream.run0(ConcurrentGenericReadInputStream.java:207)
    at stream.ConcurrentGenericReadInputStream.run(ConcurrentGenericReadInputStream.java:183)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

I double checked the sequences files, 141 R1 files and 141 R2 files, and it doesn’t seem the number of R1 and R2 are any different. And I don't understand what does "EOF marker is absent" mean.

Thanks!
Leran

**Comment by linsalrob** [comment]
One of your pairs of R1/R2 files have different numbers of sequences in them and the program we use has crashed because it didn't properly test them first.

This bit of code should find files where the number of reads are different:

Change the name of fastq to your directory with the fastq files.
```
DIR=fastq;
for R1 in $(find $DIR -name \*R1\* -printf "%f\n"); do 
     R1READS=$(wc -l $DIR/$R1 | cut -f 1 -d ' '); 
     R2READS=$(wc -l $DIR/${R1/R1/R2} | cut -f 1 -d ' ');
     if [ $R1READS != $R2READS ]; then 
        echo "File $R1: R1 reads $R1READS R2 reads $R2READS";
     fi;
done
```

I've put that into  [this file](https://github.com/shandley/hecatomb/files/7737858/count_reads.txt) in case it is easier to run

When you have figured out which file has different numbers of reads then [there are lots of ways to correct that pair of files](https://edwards.flinders.edu.au/sorting-and-paring-fastq-files/)

**Comment by shandley** [comment]
Just to follow-up on this. What was occurring with my run on the same server was the weekly purge from our temporary storage / working directory (e.g. /scratch). These files are cleaned weekly if the files have not been modified for 60 days. Fastq files for my run were 'scrubbed' and moved to a temporary trash folder and I received the exact same error message that @Leran10 did, but it wasn't due to unequal number of reads per read pair.

This may be an issue for other users who have similar file-purge rules on their servers. Should just be able to transfer the files back to the working directory and rerun.

**Comment by Leran10** [comment]
Thanks Rob!

Maybe wc -l is not the best way to get the number of reads? The results show that every files are with different numbers in R1 and R2. I applied it on our test_data as well and same there.

(out test data:)
(base) leranwang@n146:/opt/apps/labs/sahlab/software/hecatomb/test_data$ wc -l A13-04-182-06_TAGCTT_R1.fastq.gz
**18279** A13-04-182-06_TAGCTT_R1.fastq.gz
(base) leranwang@n146:/opt/apps/labs/sahlab/software/hecatomb/test_data$ wc -l A13-04-182-06_TAGCTT_R2.fastq.gz
**18488** A13-04-182-06_TAGCTT_R2.fastq.gz

I used seqkit stats to check the number of sequences in R1 and R2 and it shows that they are same.

(my data:)
(base) leranwang@n146:/scratch/sahlab/AK/AK_data$ seqkit stats M725_I9108_20175_Harris_1_NEBNextIndex1_ATCACG_S1_R1_001.fastq.gz
file                                                               format  type   num_seqs      sum_len  min_len  avg_len  max_len
M725_I9108_20175_Harris_1_NEBNextIndex1_ATCACG_S1_R1_001.fastq.gz  FASTQ   DNA   **1,270,512**  317,628,000      250      250      250
(base) leranwang@n146:/scratch/sahlab/AK/AK_data$ seqkit stats M725_I9108_20175_Harris_1_NEBNextIndex1_ATCACG_S1_R2_001.fastq.gz
file                                                               format  type   num_seqs      sum_len  min_len  avg_len  max_len
M725_I9108_20175_Harris_1_NEBNextIndex1_ATCACG_S1_R2_001.fastq.gz  FASTQ   DNA   **1,270,512**  317,628,000      250      250      250

So there might be other reasons that led to this "EOF marker is absent. The input may be truncated" issue?

**Comment by linsalrob** [comment]
Hi Leran

I noticed that you have `.gz` files and so `wc` won't work on compressed files directly. `wc` also won't work on multi-line fastq files but I haven't seen those in ages (in the original fastq spec, you could have multiple lines per sequence or quality region, but pretty much everyone abandoned those).

As you note `seqkit` or `seqtk` are the best way of counting the reads. 

(You can do it with `wc` but you need to use `gunzip -c $DIR/$R1 | wc -l`)

Rob

**Comment by Leran10** [comment]
Thanks for the information Rob!!
Leran
