### ISSUE TITLE
snakemake profiles

### ISSUE THREAD

**Issue by linsalrob** [shandley/hecatomb#56]
"Non-standard" default snakemake profiles are giving a hecatomb error. 

I have [followed Mike's snakemake profile tutorial](https://fame.flinders.edu.au/blog/2021/08/02/snakemake-profiles-updated), but then added things to both the `sbatch` command and the `default-resources`.

For example, our cluster has a `partition` setting (`general` vs `GPU`) with a default resource of `general` that has been missed by hecatomb.

We need to make sure that hecatomb is compatible with any profile, and I think we need to ensure we incorporate the users `default-resources` settings, and perhaps other settings too(?)

**Comment by beardymcjohnface** [comment]
The launcher is reading the defaults for jobs, mem and time from the run config and passing it via the command line to snakemake under --default-resources. This overwrites any declarations for default resources in the profile. It's a little bit unnecessary anyway, so I've removed it and it should be fixed in the next release.

**Comment by beardymcjohnface** [comment]
should be fixed in current version
